[tool.poetry]
name = "all-in-analytics-core"
version = "0.1.0"
description = ""
authors = ["Adam"]

[tool.poetry.dependencies]
python = "^3.12"
ipython = "^9.0.1"

[tool.poetry.group.src.dependencies]
pydantic = "*"
fastapi = "*"
uvicorn = "*"
python-dateutil = "*"
SQLAlchemy = "*"
pytz = "*"
httpx = "*"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-mock = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "*"
pre-commit = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
