"""add sb_bb_player_ids to hands

Revision ID: 52d3d811056e
Revises: 4d88a1c3a8d4
Create Date: 2026-04-12 10:33:22.220326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d3d811056e'
down_revision: Union[str, Sequence[str], None] = '4d88a1c3a8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sb_player_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bb_player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_hands_sb_player_id', 'players', ['sb_player_id'], ['player_id']
        )
        batch_op.create_foreign_key(
            'fk_hands_bb_player_id', 'players', ['bb_player_id'], ['player_id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hands', schema=None) as batch_op:
        batch_op.drop_constraint('fk_hands_bb_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_hands_sb_player_id', type_='foreignkey')
        batch_op.drop_column('bb_player_id')
        batch_op.drop_column('sb_player_id')

    # ### end Alembic commands ###
