"""add rebuys table

Revision ID: 6095f8c03fbe
Revises: 447f9697b2f2
Create Date: 2026-04-12 11:01:23.899979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6095f8c03fbe'
down_revision: Union[str, Sequence[str], None] = '447f9697b2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebuys',
    sa.Column('rebuy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_sessions.game_id'], ),
    sa.PrimaryKeyConstraint('rebuy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebuys')
    # ### end Alembic commands ###
