"""add hand_states table

Revision ID: 72219689ea6b
Revises: 6095f8c03fbe
Create Date: 2026-04-12 11:07:45.085903

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72219689ea6b'
down_revision: Union[str, Sequence[str], None] = '6095f8c03fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'hand_states',
        sa.Column('hand_state_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('hand_id', sa.Integer(), nullable=False),
        sa.Column('phase', sa.String(), nullable=False),
        sa.Column('current_seat', sa.Integer(), nullable=True),
        sa.Column('action_index', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['hand_id'],
            ['hands.hand_id'],
        ),
        sa.PrimaryKeyConstraint('hand_state_id'),
        sa.UniqueConstraint('hand_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand_states')
    # ### end Alembic commands ###
