"""add detection_corrections table

Revision ID: 9a2de4cde190
Revises: ec09e08aa2b8
Create Date: 2026-03-11 15:39:57.161618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2de4cde190'
down_revision: Union[str, Sequence[str], None] = 'ec09e08aa2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_corrections',
    sa.Column('correction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('card_position', sa.String(), nullable=False),
    sa.Column('detected_value', sa.String(), nullable=False),
    sa.Column('corrected_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['image_uploads.upload_id'], ),
    sa.PrimaryKeyConstraint('correction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_corrections')
    # ### end Alembic commands ###
