"""add card_detections table

Revision ID: dcdc3e2657a6
Revises: 731dac60f062
Create Date: 2026-03-11 14:41:45.207300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdc3e2657a6'
down_revision: Union[str, Sequence[str], None] = '731dac60f062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'image_uploads',
        sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game_sessions.game_id'],
        ),
        sa.PrimaryKeyConstraint('upload_id'),
    )
    op.create_table(
        'card_detections',
        sa.Column('detection_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('upload_id', sa.Integer(), nullable=False),
        sa.Column('card_position', sa.String(), nullable=False),
        sa.Column('detected_value', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('bbox_x', sa.Float(), nullable=True),
        sa.Column('bbox_y', sa.Float(), nullable=True),
        sa.Column('bbox_width', sa.Float(), nullable=True),
        sa.Column('bbox_height', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['upload_id'],
            ['image_uploads.upload_id'],
        ),
        sa.PrimaryKeyConstraint('detection_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_detections')
    op.drop_table('image_uploads')
    # ### end Alembic commands ###
