"""create_initial_tables

Revision ID: 731dac60f062
Revises:
Create Date: 2026-03-11 02:22:54.216551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731dac60f062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'game_sessions',
        sa.Column('game_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('game_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('game_id'),
    )
    op.create_table(
        'players',
        sa.Column('player_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('player_id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'game_players',
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game_sessions.game_id'],
        ),
        sa.ForeignKeyConstraint(
            ['player_id'],
            ['players.player_id'],
        ),
        sa.PrimaryKeyConstraint('game_id', 'player_id'),
    )
    op.create_table(
        'hands',
        sa.Column('hand_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('hand_number', sa.Integer(), nullable=False),
        sa.Column('flop_1', sa.String(), nullable=False),
        sa.Column('flop_2', sa.String(), nullable=False),
        sa.Column('flop_3', sa.String(), nullable=False),
        sa.Column('turn', sa.String(), nullable=True),
        sa.Column('river', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game_sessions.game_id'],
        ),
        sa.PrimaryKeyConstraint('hand_id'),
        sa.UniqueConstraint('game_id', 'hand_number', name='uq_hand_game_number'),
    )
    op.create_table(
        'player_hands',
        sa.Column('player_hand_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('hand_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('card_1', sa.String(), nullable=False),
        sa.Column('card_2', sa.String(), nullable=False),
        sa.Column('result', sa.String(), nullable=True),
        sa.Column('profit_loss', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['hand_id'],
            ['hands.hand_id'],
        ),
        sa.ForeignKeyConstraint(
            ['player_id'],
            ['players.player_id'],
        ),
        sa.PrimaryKeyConstraint('player_hand_id'),
        sa.UniqueConstraint('hand_id', 'player_id', name='uq_player_hand'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_hands')
    op.drop_table('hands')
    op.drop_table('game_players')
    op.drop_table('players')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
